pipeline {
    agent {
        docker {
            image 'node'
            args '-p 3000:3000'
        }
    }

    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Deployment') {
            steps {
                sh './jenkins/scripts/deploy.sh'
            }
        }
    }
}
